source: .
destination: ./_site
# A blank URL breaks the XML escape tag in sitemap
# url: https://michaelball.co
#pygments: true
lsi: true
#markdown: rdiscount

excerpt_seperator: "<!--more-->"

timezone: America/Los_Angeles

exclude: [Berkeley Websites, Templates, tools, TODO.md, README.md, LICENSE, CNAME]

#permalink: /:categories/:year/:i_month/:title/
permalink: pretty
paginate: 6
#Roughly, 1 in 5 posts will be a text post?
paginate_path: "posts/page:num"
#paginate_files:
# - blog.html
# - archive.html

#tag_page_layout: tag_page
#tag_page_dir: tag

title: Michael Ball
author: Michael Ball
version: 2.0
copy-start: 2011
copy-end: 2020
# FIXME
description: A very work in progress site. Someday, I will write more...

keywords: [Michael Ball, college, Cal,
    Berkeley, computer science, programming, cycomachead,
    cs education, teaching]


# Social Links
flickr: cycomachead
github: cycomachead
instagram: cycomachead
linkedin: pub/michael-ball/43/18a/81/
twitter: cycomachead
