source: .
destination: ./_site/
# FIXME
url: http://cycomachead.github.com/Website
safe: true
pygments: true
lsi: false
markdown: rdiscount

exclude: [Berkeley Websites, Templates, Tumblr, misc tools,
 README.md, TODO.md, LICENSE]

permalink: pretty
paginate: 6
paginate_files: index.html, archive/index.html

title: Michael Ball Photo
author: Michael Ball
version: 2.0
copy-start: 2011
copy-end: 2012
# FIXME
description: SOMETHINGHERETODO
keywords: [iPhone, apps, photography, Quad Solver, Michael Ball, college, Cal,
    Berkeley, computer science, programming, cycomachead, photo, apple, iOS,
    macs]


aboutame: michaelball
appstore: michaelball
facebook: quadsolver
flickr: cycomachead
github: cycomachead
googleplus: 109987956810230671866
instagram: cycomachead
linkedin: /pub/michael-ball/43/18a/81/
tumblr: cycomachead
twitter: cycomachead
twitterposts: michaelbphotos
youtube: cycomachead


