source: .
destination: ./_site
# A blank URL breaks the XML escape tag in sitemap
url: http://michaelballphoto.com
#pygments: true
lsi: true
#markdown: rdiscount

excerpt_seperator: "<!--more-->"

timezone: America/Los_Angeles

exclude: [Berkeley Websites, Templates, tools, TODO.md, README.md, LICENSE, CNAME]

#permalink: /:categories/:year/:i_month/:title/
permalink: pretty
paginate: 6
#Roughly, 1 in 5 posts will be a text post?
paginate_path: "posts/page:num"
#paginate_files:
# - blog.html
# - archive.html

#tag_page_layout: tag_page
#tag_page_dir: tag

title: Michael Ball Photo
author: Michael Ball
version: 2.0
copy-start: 2011
copy-end: 2013
# FIXME
description: A (mostly) daily photo blog with a bit about Apple, Macs, college life, UC Berkeley, and anything I feel like sharing.

keywords: [iPhone, apps, photography, Quad Solver, Michael Ball, college, Cal,
    Berkeley, computer science, programming, cycomachead, photo, apple, iOS,
    macs]


aboutme: michaelball
appstore: michaelball
facebook: quadsolver
flickr: cycomachead
github: cycomachead
googleplus: 109987956810230671866
instagram: cycomachead
linkedin: pub/michael-ball/43/18a/81/
tumblr: cycomachead
twitter: cycomachead
twitterposts: michaelbphotos
youtube: cycomachead


